language: c

os:
  - linux
  - osx

before_install:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -qq update; fi

install:
    - if ! [[ $TRAVIS_OS_NAME == "linux" ]]; then brew install fftw; fi
    - if ! [[ $TRAVIS_OS_NAME == "linux" ]]; then brew install gsl; fi
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get install -y libfftw3-dev; fi

script:
    - cmake --version
    - mkdir build
    - cmake -H. -Bbuild
    - make -Cbuild
    - build/angpow angpow_bench1.ini
    - build/angpow angpow_bench2.ini
    - build/angpow angpow_bench3.ini
    - build/angpow angpow_bench4.ini
    - build/angpow angpow_bench5.ini
    - build/angpow angpow_bench6.ini
